---
- name: Install Python and pip
  apt:
    name: ["python3", "python3-pip"]
    state: present

- name: Install Flask
  pip:
    name: flask

- name: Copy application code
  copy:
    src: ../../../app/
    dest: /opt/app